version: '3'

services:
  mongo:
    image: mongo
    restart: always
  db:
    image: mysql
    restart: always
    expose: 
          - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
  web:
    build: .
    command: ["./wait-for-it.sh", "mongo:27017", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "80:8000"
      - "9527:22"
    depends_on:
      - mongo
      - db
    restart: always