version: '3'

services:
  mongo:
    image: mongo
    restart: always
  mysql:
    image: mysql
    restart: always
    expose: 
          - "3306"
    environment:
      - MYSQL_DATABASE=udiclab
      - MYSQL_ROOT_PASSWORD=udiclab
  web:
    build: .
    command: ["./wait-for-it.sh", "mongo:27017", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - mongo
      - mysql
    restart: always