version: '3'

services:
  db:
    image: davidtnfsh/mongo
  web:
    build: .
    command: ["./wait-for-it.sh", "db:27017", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db