version: '3'

services:
  mongo:
    image: mongo
    restart: always
  postgres:
    image: postgres
    restart: always
  web:
    build: .
    command: ["./wait-for-it.sh", "mongo:27017", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - mongo
      - postgres
    restart: always
